### ISSUE TITLE
Add confirm page at the end of the workflow.

### ISSUE THREAD

**Issue by SamuelPelletierEvraire** [ai-cfia/fertiscan-frontend#53] opened 2024-06-06 14:01 UTC
## Description
Once the user has validated all the fields and confirmed the data, the user shall be prompted a confirmpage

## Tasks
- [x] Create a ConfirmPage
- [x] Prompt the page when the user finishes the process

## Acceptance criteria
- [x] The page is not shown if an error occured
- [x] The user is automatically redirected to the home page

**Comment by Youllou** [comment] 2024-06-20 13:40
Duplicate of #47

**Comment by k-allagbe** [comment] 2024-09-03 14:46
@Youllou @SamuelPelletierEvraire, is this still relevant?

**Comment by Youllou** [comment] 2024-09-03 15:00
It will be fixed with #175 in #219

**Comment by k-allagbe** [comment] 2024-09-14 01:13
Tested, works as expected.

**Closed** 2024-09-14 01:14 UTC
