### ISSUE TITLE
As a user, I want to be able to save and retrieve the scanned labels to and from a database.

### ISSUE THREAD

**Issue by Youllou** [ai-cfia/fertiscan-frontend#174] opened 2024-07-24 17:38 UTC
## Description  

**Problem Statement**
Right now the application only provides a temporary saved document and does not give the ability to retrieve a previously scanned form

**Acceptance Criteria**
- [ ] #175 
- [ ] #53 
- [ ] #176
- [ ] #178

**Comment by Endlessflow** [comment] 2024-07-25 18:40
We have reached a consensus that this Epic may potentially be a duplicate of the Epic bellow:
https://github.com/ai-cfia/fertiscan-backend/issues/82

**Closed by Endlessflow** 2024-07-25 18:40 UTC
Labels: enhancement, epic
