### ISSUE TITLE
As a user, I want to see the correct favicon and title.

### ISSUE THREAD

**Issue by nmeraihi** [ai-cfia/fertiscan-frontend#173] opened 2024-07-24 15:52 UTC
# Correct the title page and favicon on the tab

### Bug Summary:
The title page and the favicon on the tab are not displaying correctly. The title currently reads "Vite + React + TS" instead of the appropriate project name, and the CFIA favicon is missing on the browser tab.

### Steps to Reproduce:
1. Open the browser and go to `fertiscan.inspection.alpha.canada.ca`.
2. Observe the tab title and small favicon/logo

### Expected Behavior:
The tab should display the correct title relevant to the project and the favicon should be visible on the tab.

![image](https://github.com/user-attachments/assets/010fe68e-8527-4bbb-b7a5-4dfd7866281b)

**Comment by Youllou** [comment] 2024-07-26 13:28
duplicate of #162 and merged in #164

**Closed by Youllou** 2024-07-26 13:28 UTC
Labels: bug, duplicate
